export const SEARCH_ACCOUNTS = 'SEARCH_ACCOUNTS';
export const SEARCHED_ACCOUNTS = 'SEARCHED_ACCOUNTS';
export const ACCOUNT_DETAIL_FIND = 'ACCOUNT_DETAIL_FIND';
export const ACCOUNT_DETAIL_FOUND = 'ACCOUNT_DETAIL_FOUND';
