export const ACCOUNTS_SEARCH = 'ACCOUNTS_SEARCH';
export const ACCOUNTS_SEARCHED = 'ACCOUNTS_SEARCHED';
export const ACCOUNT_DETAIL_FIND = 'ACCOUNT_DETAIL_FIND';
export const ACCOUNT_DETAIL_FOUND = 'ACCOUNT_DETAIL_FOUND';
