export const NAVIGATION_FIND = 'NAVIGATION_FIND';
export const NAVIGATION_FOUND = 'NAVIGATION_FOUND';
export const NAVIGATION_ADD_ALL = 'NAVIGATION_ADD_ALL';
export const NAVIGATION_ADDED_ALL = 'NAVIGATION_ADDED_ALL';
export const NAVIGATION_REMOVE = 'NAVIGATION_REMOVE';
export const NAVIGATION_REMOVED = 'NAVIGATION_REMOVED';
export const NAVIGATION_MODIFY = 'NAVIGATION_MODIFY';
export const NAVIGATION_MODIFIED = 'NAVIGATION_MODIFIED';

