export const NAVIGATION_FIND = 'NAVIGATION_FIND';
export const NAVIGATION_FOUND = 'NAVIGATION_FOUND';
export const NAVIGATION_ADD = 'NAVIGATION_ADD';
export const NAVIGATION_ADDED = 'NAVIGATION_ADDED';
export const NAVIGATION_REMOVE = 'NAVIGATION_REMOVE';
export const NAVIGATION_REMOVED = 'NAVIGATION_REMOVED';
