spring:
  jpa:
    database: h2
    show-sql: true
    hibernate:
      connection:
        charSet: UTF-8
      ddl-auto: create-drop

    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.default_batch_fetch_size: 50
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      org.hibernate.envers.audit_table_suffix: _history
      org.hibernate.envers.revision_field_name: revision
      org.hibernate.envers.revision_type_field_name: revision_type


  datasource:
    url: jdbc:h2:mem:cave;DB_CLOSE_ON_EXIT=FALSE;AUTOCOMMIT=OFF
    username: sa
    password:

  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.web: debug
    org.springframework.boot: debug
    org.hibernate: error

cave:
  crypto:
    key: fab5609c1480a897

